#!/bin/bash

# Manual Migration Guide for Out Sports QC
# Since Supabase CLI requires special setup, here are manual steps

echo "📋 MANUAL MIGRATION GUIDE - Out Sports QC"
echo "=========================================="
echo ""
echo "Since automatic migration isn't available, please follow these manual steps:"
echo ""

echo "🎯 STEP 1: Website Feedback Table"
echo "--------------------------------"
echo "Purpose: Stores user bug reports and suggestions"
echo ""
echo "👉 Instructions:"
echo "1. Open your Supabase dashboard: https://supabase.com/dashboard"
echo "2. Navigate to: SQL Editor"
echo "3. Copy and paste the contents of: supabase/migrations/create_website_feedback_table.sql"
echo "4. Click 'Run' to execute the SQL"
echo ""

echo "🎯 STEP 2: Registration Details Table"
echo "------------------------------------"
echo "Purpose: Admin-configurable registration form fields (the 6 boxes at top of registration form)"
echo ""
echo "👉 Instructions:"
echo "1. In the same SQL Editor"
echo "2. Copy and paste the contents of: supabase/migrations/20250730_add_registration_details.sql"
echo "3. Click 'Run' to execute the SQL"
echo ""

echo "🎯 STEP 3: Fix Locations Table"
echo "------------------------------"
echo "Purpose: Fixes locations table for admin location management"
echo ""
echo "� Instructions:"
echo "1. In the same SQL Editor"
echo "2. Copy and paste the contents of: supabase/migrations/fix_locations_table.sql"
echo "3. Click 'Run' to execute the SQL"
echo ""

echo "�📁 FILE LOCATIONS:"
echo "=================="
echo "File 1: $(pwd)/supabase/migrations/create_website_feedback_table.sql"
echo "File 2: $(pwd)/supabase/migrations/20250730_add_registration_details.sql"
echo "File 3: $(pwd)/supabase/migrations/fix_locations_table.sql"
echo ""

echo "✅ WHAT YOU'LL GET AFTER RUNNING THESE:"
echo "======================================="
echo ""
echo "🔧 New Admin Dashboard Features:"
echo "  • Website Feedback section - View/manage user bug reports (improved priority and delete styling)"
echo "  • Registration Details editor - Configure the 6 info boxes on registration form"
echo "  • Location Management - Create/edit game locations (city, state, zip now save properly)"
echo "  • Games table - Added Season, Year, and Sport columns for better organization"
echo "  • Games archiving - New 'Archived' status for inactive season games"
echo "  • Fixed Active checkbox issue - Checkboxes now work properly for reactivating items"
echo "  • Sports Management - Create/edit sports with Season/Year organization (Add New Sport button now works)"
echo "  • Auto-Generated Titles - Sports titles now auto-generate as '[Season] [Year] [Sport] League'"
echo "  • Auto-Generated Roster Paths - Teams routes auto-generate as '#[season]-[year]-[sport]-teams'"
echo "  • Removed Roster Path Input - No manual roster path entry needed, it's automatic"
echo "  • Year validation - New sports: min current year (2025), Edit sports: min 2025 (league start)"
echo "  • Smart Game Creation - Sport dropdown shows only Active/Coming Soon sports with season/year info"
echo ""
echo "🌐 Updated User Experience:"
echo "  • Menu: 'General Info' is now 'About Us'"
echo "  • Join buttons redirect to '#registration'"
echo "  • Menu: 'Give Feedback' is now 'Give Website Feedback'"
echo "  • Registration form uses your admin-configured values"
echo "  • Website feedback modal prevents page scrolling when open"
echo "  • Social media cleaned up - removed Discord and Twitter, kept Facebook and Instagram"
echo "  • Dynamic Sports Menu - Menu items automatically generated from admin sports data"
echo "  • Smart Sport Navigation - Schedule/Teams links: #[season]-[year]-[sport]-schedule/teams (all lowercase)"
echo "  • Homepage Sports Cards - Filtered by Active/Coming Soon, custom sorted, auto-routed to teams page"
echo ""
echo "🗺️  Fixed Map Display:"
echo "  • Maps now show only locations stored in database"
echo "  • Location city, state, and ZIP code fields save correctly"
echo "  • Database locations take priority over static file data"
echo ""

echo "🎯 TESTING YOUR CHANGES:"
echo "========================"
echo "1. After running the SQL migrations:"
echo "2. Visit your admin dashboard"
echo "3. Go to 'Registrations' → 'Registration Details' tab"
echo "4. Update the 6 text fields (Sport, Season, Duration, Game Time, Location, Team Size)"
echo "5. Visit the registration page to see your changes"
echo "6. Test 'Website Feedback' section - you can now delete entries"
echo "7. Test 'Locations' section - you can now create/edit game locations"
echo "8. Test 'Sports Info' section - Click 'Add New Sport' to create sports with Season/Year"
echo "9. Notice Display Title and Roster Path are auto-generated (no manual input needed)"
echo "10. Create a new active sport and check the main website menu for dynamic sports dropdown"
echo "11. Test 'Games' section - Sport dropdown now shows only Active/Coming Soon sports"
echo "12. Verify homepage sports cards link to teams pages with lowercase routing"
echo "13. Check navigation menu uses lowercase routing: #[season]-[year]-[sport]-schedule/teams"
echo ""

echo "📝 SQL FILES CONTENT:"
echo "===================="
echo ""
echo "🗂️  File 1 Content (Website Feedback):"
echo "--------------------------------------"
cat "$(pwd)/supabase/migrations/create_website_feedback_table.sql"
echo ""
echo ""
echo "🗂️  File 2 Content (Registration Details):"
echo "------------------------------------------"
cat "$(pwd)/supabase/migrations/20250730_add_registration_details.sql"
echo ""
echo ""
echo "🗂️  File 3 Content (Locations Table Fix):"
echo "-----------------------------------------"
cat "$(pwd)/supabase/migrations/fix_locations_table.sql"
echo ""

echo "✅ SUMMARY: Copy and run all 3 SQL files in your Supabase dashboard's SQL Editor!"
